### ISSUE TITLE
Error on first `cnd up` asking you to do `cnd up`

### ISSUE THREAD

**Issue by rlamana** [okteto/cnd#100]
**Describe the bug**
First time `cnd up` is executed and error message is displayed asking you to do `cnd up` first. If you execute it again it will normally work.

**To Reproduce**
1. From command line go to the directory where `cnd.yml` is.
2. Execute `cnd up`.
3. Error message is displayed.
4. Execute `cnd up` again.
5. Everything works normally.

**Expected behavior**
`cnd up` should properly work the first time is launched.

**Screenshots**
Output shown:
```
> cnd up
Activating your cloud native development environment...
Error: cloud native environment is not initialized. Please run 'cnd up' first
```

**Desktop (please complete the following information):**
 - CND version 0.3.4

**Comment by rberrelleza** [comment]
@rlamana can you share your cnd.yml and k8s manifest? Can't reproduce the issue so far.

**Comment by rlamana** [comment]
manifests and cnd.yml are those of the voting-app example on the repo. 
It seems to be working now and I cannot repro anymore either. For quite a few hours it was happening every time I did a `cnd up`. I will close this issue and reopen if I ever get `cnd` on that weird state again.
